amazon:
  access:
    key: AKIAJ2M4Q3TC64RPDBYA
    secret-key: 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
  region: ap-south-1
  end-point:
    url: dynamodb.ap-south-1.amazonaws.com
server:
  port: 9001