amazon:
  access:
    key: <access key id >
    secret-key: <access secret key aws>
  region: <region of dynamo db>
  end-point:
    url: dynamodb.ap-south-1.amazonaws.com
server:
  port: <defined port of yours>
